# CNN Training Configuration
dataset_folder: processed/dataset_v1/
class_mapping: class_mapping.json

project_version: development_v1
environment: local

# Model configuration
model_info:
  architecture: resnet50
  pretrained: true
  # checkpoint: efficientnet_b0_v1/best.pt
  num_classes: 2
  dropout: [0.1, 0.5]           # OPTUNA RANGE
  frozen_layers:
    efficientnet_b0: [0, 6]     # OPTUNA RANGE
    efficientnet_b3: [0, 7]     # OPTUNA RANGE
    resnet50: [0, 3]            # OPTUNA RANGE
    resnet101: [0, 4]           # OPTUNA RANGE

# Training parameters
training_params:
  n_trials: 4
  epochs: 12
  batch_size: 32 
  learning_rate: [1e-5, 1e-2]   # OPTUNA RANGE (log scale)
  weight_decay: [1e-5, 1e-2]    # OPTUNA RANGE (log scale)

  optimizer: [adamw, adam, sgd] # OPTUNA CHOICE
  warmup_epochs: 3
  label_smoothing: 0.1

# Data augmentation  
augmentation:
  # EfficientNet specific - different variants use different input sizes
  
  random_rotation: [5, 25]      # OPTUNA RANGE
  random_flip: 0.5
  blur_probability: 0.1
  color_jitter:
    brightness: [0.0, 0.3]      # OPTUNA RANGE
    contrast: [0.0, 0.3]        # OPTUNA RANGE
    saturation: 0.1
    hue: 0.05
  normalize:
    mean: [0.485, 0.456, 0.406] # ImageNet stats
    std: [0.229, 0.224, 0.225]

# Validation settings
validation:
  # split_ratio: 0.2
  metrics: [accuracy, f1_macro, precision_macro, recall_macro]
  
# Early stopping
early_stopping:
  monitor: val_accuracy
  patience: 5
  min_delta: 0.001