input_folder: interim/
output_folder: processed/dataset_v2

output_storage: drive

split_datasets:
  train:
    cctv_people: 1.0
    cctv_screenshots: 0.9
    drone_people: 0.9
    cctv_kaggle: 0.1
  val:
    cctv_screenshots: 0.1
    drone_people: 0.1
  test:
    cctv_test: 1.0

target_classes:
  - female
  - male