# CNN Training Configuration
dataset_folder: processed/dataset_v2/
class_mapping: class_mapping.json

project_version: development
environment: local

# Model configuration
model_info:
  architecture: efficientnet_b0
  pretrained: true
  # checkpoint: efficientnet_b0_v1/best.pt
  num_classes: 2
  dropout: 0.265
  frozen_layers: 1

# Training parameters
training_params:
  epochs: 12
  batch_size: 32 
  learning_rate: 0.0072
  weight_decay: 1.1036

  optimizer: adam
  warmup_epochs: 3
  label_smoothing: 0.1

# Data augmentation  
augmentation:
  # EfficientNet specific - different variants use different input sizes
  resize: 224  # If not provided, defined in context object creation

  # Spatial transforms
  scale_factor: 0.2
  perspective_probability: 0.1
  perspective_distortion: 0.05
  translate: 0.05
  shear: 5
  random_rotation: 22.43
  random_flip: 0.5

  # Blur effects
  blur_probability: 0.1
  motion_blur_probability: 0.05
  motion_blur_kernel: 5

  # Color adjustments
  color_jitter:
    brightness: 0.01
    contrast: 0.29
    saturation: 0.1
    hue: 0.05

  # Advanced augmentations
  gamma: 0.1
  random_erasing_probability: 0.1
  random_erasing_scale: [0.02, 0.10]

  # Standard normalization
  normalize:
    mean: [0.485, 0.456, 0.406] # ImageNet stats
    std: [0.229, 0.224, 0.225]

# Validation settings
validation:
  # split_ratio: 0.2
  metrics: [accuracy, f1_macro, precision_macro, recall_macro]
  
# Early stopping
early_stopping:
  monitor: val_accuracy
  patience: 5
  min_delta: 0.001